### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by arduano** [arduano/xsynth#73]
@MyBlackMIDIScore how do I contact you lol, I need to discuss something about your soundfont program change code that breaks some midis, among other things

You don't use discord anymore, do you have a preferred place to talk?

**Comment by MyBlackMIDIScore** [comment]
@arduano How did I only just see that I am actually so sorry, I didn't notice this at all 
I mostly use Facebook or Instagram for chatting (not preferred but I wouldn't mind), but I also have a Telegram account I use sometimes. Aside from that I can talk here or by email (but as it may be clear I don't check those very often lol).

**Comment by arduano** [comment]
Hey, yeah I fixed the issue in question I think, but also I guess it's ok if you don't really want to go out of your way to work on this anymore (because communication hard), you've done so much already

Not sure how much I'll be maintaining this myself too
